#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d Α Β Γ Δ Π Σ Υ Φ Ψ Ω
# α β γ δ ε ζ η π φ λ
# I II III IV V VI VII VIII IX X
# bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focused_border_color "#fabd2f"
#bspc config normal_border_color "#3c3836"

#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
feh --bg-center /$HOME/Pictures/Wallpapers/dune_resized.png

mod=Mod4
bspc keybind $mod+r bspc wm -r
